FROM golang:latest

WORKDIR /app

COPY . .

RUN go get -u github.com/gorilla/mux
RUN go get -u gorm.io/gorm
RUN go get -u gorm.io/driver/sqlite
RUN go get -u gopkg.in/gomail.v2
RUN go get -u github.com/robfig/cron/v3
RUN go get github.com/stretchr/testify

RUN go build -o currency_exchange .

EXPOSE 8080

CMD ["./currency_exchange"]
